# Site
name: "Odisha.First."
<<<<<<< HEAD
description: "Everythig about Odisha."
=======
description: "Everythig about odisha."
>>>>>>> 6b075a87b2aac343170ee0404a0266f4d64369c7
meta_description: "Odisha First Official Website"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
url: https://odisha.top
enforce_ssl: odisha.top
google_analytics: 'UA-126196218-1'
disqus: 'https-odisha-top'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

# Authors
authors:
  Admin:
    name: Admin
    display_name: Admin
    gravatar: author-thumb-admin-200x200.jpg
<<<<<<< HEAD
    email: web@cuttack.top
=======
    email: web@odisha.top
>>>>>>> 6b075a87b2aac343170ee0404a0266f4d64369c7
    web: https://odisha.top
    facebook: https://facebook.com/odishafirstofficial
    twitter: https://twitter.com/odishafirst
    description: "Admins of the website."
  #john:
  #  name: John
  #  display_name: John
  #  gravatar: b1cc14991db7a456fcd761680bbc8f81
  #  email: wowthemesnet@gmail.com
  #  web: https://www.wowthemes.net
  #  twitter: https://twitter.com/wowthemesnet
  #  description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
    - authors
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 10
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge
